spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id : r1
            uri : http://localhost:8080/
            predicates:
              - Path=/customers/**
          - id : r2
            uri : http://localhost:8082/
            predicates:
              - Path=/accounts/**
  application:
    name: lol
server:
  port: 8088